In [76]:
import torch

br = torch.tensor([[0.0, 0, 0], [0, 0, 0], [0, 0, 5]])  # blob bottom-right

tl = torch.tensor([[5.0, 0, 0], [0, 0, 0], [0, 0, 0]])  # blob top-left

print("bottom-right mean:", br.mean().item())
print("top-left     mean:", tl.mean().item())


bottom-right mean: 0.5555555820465088
top-left     mean: 0.5555555820465088


In [77]:
a = torch.softmax(br.reshape(-1), dim=-1)  # flatten 3x3 -> 9, softmax over all 9
print(a.reshape(3, 3))
print("sums to:", a.sum().item())


tensor([[0.0064, 0.0064, 0.0064],
        [0.0064, 0.0064, 0.0064],
        [0.0064, 0.0064, 0.9489]])
sums to: 0.9999999403953552


In [78]:
br = torch.tensor(
    [
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 15],
    ],
    dtype=torch.float64,
)
a = torch.softmax(br.reshape(-1), dim=-1)  # flatten 3x3 -> 9, softmax over all 9
print(a.reshape(3, 3))
print("sums to:", a.sum().item())


tensor([[0.0064, 0.0064, 0.0064],
        [0.0064, 0.0064, 0.0064],
        [0.0064, 0.0064, 0.9489]], dtype=torch.float64)
sums to: 1.0


In [79]:
v, u = torch.meshgrid(torch.linspace(-1, 1, 3), torch.linspace(-1, 1, 3), indexing="ij")
print("u (column / x):")
print(u)
print("v (row / y):")
print(v)


u (column / x):
tensor([[-1.,  0.,  1.],
        [-1.,  0.,  1.],
        [-1.,  0.,  1.]])
v (row / y):
tensor([[-1., -1., -1.],
        [ 0.,  0.,  0.],
        [ 1.,  1.,  1.]])


In [80]:
x = (a.reshape(3, 3) * u).sum()
y = (a.reshape(3, 3) * v).sum()
print(f"x = {x:.4f}   y = {y:.4f}")


x = 0.9425   y = 0.9425


In [82]:
a_tl = torch.softmax(tl.reshape(-1), dim=-1).reshape(3, 3)
print(f"x = {(a_tl * u).sum():.4f}   y = {(a_tl * v).sum():.4f}")


x = -0.9425   y = -0.9425


In [ ]:
for T in [5.0, 1.0, 0.2]:
    a_T = torch.softmax(br.reshape(-1) / T, dim=-1).reshape(3, 3)
    print(f"T={T:4}:  x={(a_T * u).sum():+.4f}  y={(a_T * v).sum():+.4f}")


T= 5.0:  x=+0.1603  y=+0.1603
T= 1.0:  x=+0.9425  y=+0.9425
T= 0.2:  x=+1.0000  y=+1.0000


In [ ]:
two = torch.tensor([[4.0, 0, 0], [0, 0, 0], [0, 0, 5]])
for T in [1.0, 0.5, 0.2, 0.05]:
    a_T = torch.softmax(two.reshape(-1) / T, dim=-1).reshape(3, 3)
    print(f"T={T:5}:  x={(a_T * u).sum():+.4f}  y={(a_T * v).sum():+.4f}")


T=  1.0:  x=+0.4467  y=+0.4467
T=  0.5:  x=+0.7614  y=+0.7614
T=  0.2:  x=+0.9866  y=+0.9866
T= 0.05:  x=+1.0000  y=+1.0000


In [100]:
f = torch.tensor([[0.0, 0, 0], [0, 0, 0], [0, 0, 5]], requires_grad=True)
x = (torch.softmax(f.reshape(-1), -1).reshape(3, 3) * u).sum()
x.backward()
print("softmax  dx/df:\n", f.grad.round(decimals=4))

g = torch.tensor([[0.0, 0, 0], [0, 0, 0], [0, 0, 5]], requires_grad=True)
x2 = u.reshape(-1)[g.reshape(-1).argmax()]
print("\nargmax   x:", x2.item(), "  requires_grad:", x2.requires_grad)

softmax  dx/df:
 tensor([[-0.0124, -0.0060,  0.0004],
        [-0.0124, -0.0060,  0.0004],
        [-0.0124, -0.0060,  0.0546]])

argmax   x: 1.0   requires_grad: False


In [ ]:
for w in [0.0, 0.25, 0.5, 0.75, 1.0]:
    m = torch.tensor([[0.0, 0, 0], [0, 0, 0], [0, 5 * w, 5 * (1 - w)]])
    a_m = torch.softmax(m.reshape(-1), -1).reshape(3, 3)
    print(
        f"w={w}: softmax x={(a_m * u).sum():+.4f}   argmax x={u.reshape(-1)[m.reshape(-1).argmax()]:+.1f}"
    )


w=0.0: softmax x=+0.9425   argmax x=+1.0
w=0.25: softmax x=+0.7832   argmax x=+1.0
w=0.5: softmax x=+0.3565   argmax x=+0.0
w=0.75: softmax x=+0.0470   argmax x=+0.0
w=1.0: softmax x=+0.0000   argmax x=+0.0
